primary:
    base: '#181818'
    light: '#d9d2d0'
    dark: '#000000'
accent:
    base: '#b5975b'
    light: '#d2b16e'
secondary:
    base: '#381d19'
foreground:
    base: '#5bc0c6'
background:
    base: '#e9e9e9'
    light: '#ffffff'
    dark: '#dddddd'
